# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "https://cdn.cocoapods.org/"

target 'videoClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for videoClip
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SDWebImage'
  pod 'SDWebImage/GIF'
end
